### ISSUE TITLE
Immutable.java:65-68: Let's prevent modifications to arrays...

### ISSUE THREAD

**Issue by dmarkov** [jcabi/jcabi-aspects#49]
Puzzle `33-e5af3af3` in `src/main/java/com/jcabi/aspects/Immutable.java:65-68` has to be resolved: Let's prevent modifications to arrays having this annotation, somehow. Perhaps we can create an aspect that will throw an exception should something try to write into the array. See https://bugs.eclipse.org/bugs/show_bug.cgi?id=157031

If you have any technical questions, don't ask me, submit new tickets instead

**Comment by yegor256** [comment]
@dmarkov assign somebody else here pls

**Comment by dmarkov** [comment]
> @dmarkov assign somebody else here pls

@yegor256 got it, someone else will be assigned soon

**Comment by dmarkov** [comment]
@nhekfqn it's yours, please go ahead

**Comment by dmarkov** [comment]
@super132 it's your task, go ahead

**Comment by super132** [comment]
@dmarkov , this task is waiting for #157. Thanks.

**Comment by dmarkov** [comment]
> @dmarkov , this task is waiting for #157. Thanks.

@super132 ok, let's wait for #157

**Comment by super132** [comment]
@dmarkov , as per advised by @yegor256 in #157 , this ticket should be postponed for unknown amount of time. Thanks.

**Comment by super132** [comment]
@dmarkov , since this issue is going to be on hold for unknown amount of time. Would you consider this to be "postponed" and free this up from my task list? Will I get paid as well? Thanks.

**Comment by yegor256** [comment]
@dmarkov please postpone this issue

**Comment by dmarkov** [comment]
> @dmarkov please postpone this issue

@yegor256 thanks, I added the "postponed" tag

**Comment by dmarkov** [comment]
> @dmarkov please postpone this issue

@yegor256 no problem, I will try to find somebody else

**Comment by dmarkov** [comment]
@yegor256 FYI, the issue we were waiting for (#157) is fixed

**Comment by dmarkov** [comment]
@yamstranger it's yours, please go ahead

**Comment by YamStranger** [comment]
@dmarkov Please check #157 ticket. It is not fixed, just closed. Just check this comment "@super132 many thanks for the analysis you made... unfortunately, none of these options look good to me :( I think we should just postpone task #49 for unknown amount of time."  and next "@super132 no, this one is not a valid bug, it's more a discussion ticket. I think you should just close it". So it is not valid but too and it must be postponed  for unknown amount of time.

**Comment by YamStranger** [comment]
@dmarkov please postpone this issue

**Comment by yegor256** [comment]
@dmarkov pls postpone this task

**Comment by YamStranger** [comment]
@dmarkov please postpone this issue

**Comment by yegor256** [comment]
@dmarkov postpone this

**Comment by dmarkov** [comment]
> @dmarkov please postpone this issue

@yamstranger OK, will do

**Comment by dmarkov** [comment]
> @dmarkov postpone this

@yegor256 sure, thanks, I added "postponed" label to it

**Comment by dmarkov** [comment]
> @dmarkov postpone this

@yegor256 all right, we'll find someone else for this task

**Comment by dmarkov** [comment]
@yegor256 Thanks all, I am closing
